@your_store_register_feature
Feature: User Register users to Your Store
  As a new user,
  I want to register a new user and validate the error messages generated by the system,
  So that I can access my account.

  Background:
    Given the user is on the registration page of Your Store

  @YS-1 @regression_test
  Scenario: Validate correct functionality when a new user is registered
    Given the user can create a random user
    And the user enters the random user's data
    When the user submits the registration form
    Then the user should see a successful registration message

  @YS-2
  Scenario: Validate error message when trying to register an existing user
    Given the user enters an existing user in a test file
    When the user submits the registration form
    Then the user should see a user already exists error message

  @YS-3
  Scenario Outline: Validate error message when try to register a user with one empty param
    Given the user enters an existing user with empty params
      | firstName   | lastName   | email   | telephone   | password   | passwordConfirm   | subscribe   | privacy   |
      | <firstName> | <lastName> | <email> | <telephone> | <password> | <passwordConfirm> | <subscribe> | <privacy> |
    When the user submits the registration form
    Then the user should see an error message "<param>" is void

    Examples:
      | firstName | lastName  | email         | telephone  | password | passwordConfirm | subscribe | privacy | param           |
      |           | lastName1 | asd@gomal.com | 8147805173 | clave1   | clave1          | false     | true    | firstName       |
      | name1     |           | asd@gomal.com | 8147805173 | clave1   | clave1          | true      | false   | lastName        |
      | name1     | lastName1 |               | 8147805173 | clave1   | clave1          | true      | true    | email           |
      | name1     | lastName1 | asd@gomal.com |            | clave1   | clave1          | true      | true    | telephone       |
      | name1     | lastName1 | asd@gomal.com | 8147805173 |          | clave1          | true      | true    | password        |
      | name1     | lastName1 | asd@gomal.com | 8147805173 | clave1   |                 | true      | true    | passwordConfirm |

  @YS-4
  Scenario: Validate error message when try to register a user without privacy politics
    Given the user enters an existing user in a test file without privacy
    When the user submits the registration form
    Then the user should see a an error message when the register form doesn't have a privacy check OK
